name: Build and create release

on: workflow_dispatch

permissions:
  contents: read

jobs:
    generate-fonts:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
          with:
            submodules: true
        # setup-python does not work with
        # fontforge apt package so we'll be
        # using the distro's own python install.
        #
        #- name: Set up Python 3.10
        #  uses: actions/setup-python@v3
        #  with:
        #    python-version: "3.10"
        - name: install fontforge
          run: |
            sudo apt install python3-fontforge
        - name: generate.py
          run: |
            python3 generate.py
